[package]
name = "relay-protocol-derive"
authors = ["Sentry <oss@sentry.io>"]
description = "Derives for Relay's protocol traits"
homepage = "https://getsentry.github.io/relay/"
repository = "https://github.com/getsentry/relay"
version = "24.6.0"
edition = "2021"
license-file = "../LICENSE.md"
publish = false

[lints]
workspace = true

[dependencies]
quote = { workspace = true }
syn = { workspace = true }
synstructure = { workspace = true }
proc-macro2 = { workspace = true }

[lib]
proc-macro = true
