[package]
name = "relay-auth"
authors = ["Sentry <oss@sentry.io>"]
description = "Authentication and crypto for Relay"
homepage = "https://getsentry.github.io/relay/"
repository = "https://github.com/getsentry/relay"
version = "20.6.0"
edition = "2018"
license-file = "../LICENSE"
publish = false

[dependencies]
base64 = "0.10.1"
chrono = "0.4.7"
ed25519-dalek = "0.9.1"
failure = "0.1.5"
rand = "0.6.5"
relay-common = { path = "../relay-common" }
serde = { version = "1.0.98", features = ["derive"] }
serde_json = "1.0.40"
sha2 = "0.8.1"
