[package]
name = "document-metrics"
version = "0.1.0"
authors = ["Sentry <oss@sentry.io>"]
description = "Generates documentation for metrics"
homepage = "https://getsentry.github.io/relay/"
repository = "https://github.com/getsentry/relay"
edition = "2021"
publish = false

[dependencies]
anyhow = { workspace = true }
clap = { version = "4.1.4", features = ["derive"] }
serde = { version = "1.0.114", features = ["derive"] }
serde_json = "1.0.55"
serde_yaml = "0.9.17"
syn = { version = "1.0.39", features = ["full"] }

[dev-dependencies]
insta = "1.31.0"
