[package]
name = "document-metrics"
version = "0.1.0"
authors = ["Sentry <oss@sentry.io>"]
description = "Generates documentation for metrics"
homepage = "https://getsentry.github.io/relay/"
repository = "https://github.com/getsentry/relay"
edition = "2018"
publish = false

[dependencies]
anyhow = "1.0.32"
paw = "1.0.0"
serde = { version = "1.0.114", features = ["derive"] }
serde_json = "1.0.55"
serde_yaml = "0.8.13"
structopt = { version = "0.3.16", features = ["paw"] }
syn = "1.0.39"

[dev-dependencies]
insta = "1.19.0"
