[package]
name = "generate-schema"
version = "0.1.0"
authors = ["Sentry <oss@sentry.io>"]
description = "Generates an event payload schema file"
homepage = "https://getsentry.github.io/relay/"
repository = "https://github.com/getsentry/relay"
edition = "2021"
publish = false

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }
relay-event-schema = { path = "../../relay-event-schema", features = [
    "jsonschema",
] }
serde_json = { workspace = true }
