skip_tags: true

branches:
  only:
    - master
    - /^release\/[\d.]+$/

cache:
  - '%USERPROFILE%\.cargo'
  - '%LOCALAPPDATA%\Mozilla\sccache'

environment:
  ZEUS_HOOK_BASE:
    secure: dcqtt6sxxBV0tDkXmPZOyz96KWmjtSz6ZqRd9mw9GXC/C4Zcwqofxt2Kh4EP7hPEFIewRRl6xkhW53HgItdt7iVmFSHuufpGoSpzse8cgg3zfE08f/u0a2EOvuRjdtoi4E/9Znrj2HY+CC+G4j2UKWzp6EcSc++qbgSMl1h6zMs=
  CARGO_HTTP_CHECK_REVOKE: false
  matrix:
#    - channel: stable
#      arch: i686
    - channel: stable
      arch: x86_64

build:
  verbosity: minimal

install:
  # Push job information to Zeus
  - npm install -g @zeus-ci/cli
  - zeus job update --status=pending -B "%APPVEYOR_PULL_REQUEST_TITLE%" -J "%APPVEYOR_JOB_NAME%"
  # Install the rest
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %arch%-pc-windows-msvc
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV
  - sccache --version || cargo install sccache --no-default-features --git https://github.com/mozilla/sccache
  - set RUSTC_WRAPPER=sccache

build_script:
  - cargo build --all --locked

test_script:
  - C:\MinGW\bin\mingw32-make cargotest
  - C:\MinGW\bin\mingw32-make test-process-event CARGO_ARGS="--release"
  - C:\MinGW\bin\mingw32-make clean-target-folder

on_success:
  - zeus upload -t "application/octet-stream" -n semaphore-Windows-%arch%.exe .\target\release\semaphore.exe
  - zeus job update --status=passed

on_failure:
  - zeus job update --status=failed
