site_name: Sentry Relay
repo_url: https://github.com/getsentry/relay
site_author: Sentry
theme:
  name: material

nav:
  - index.md
  - options.md
  - project-config.md
  - metrics.md
  - PII and datascrubbing:
    - pii-config/index.md
    - pii-config/types.md
    - pii-config/methods.md
    - pii-config/selectors.md

  - Architecture:
    - architecture/index.md
    - architecture/actors.md
    - architecture/ingest-event-path.md
    - architecture/project-configuration.md

  - event-schema/index.md

markdown_extensions:
  - admonition: {}
  - tables: {}
  - codehilite: {}

  # Config for diagrams
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format

plugins:
  - search
  # Used in event schema docs
  - macros

  - exclude:
      glob:
        - event-schema/event.schema.md

extra_css:
  # Config for diagrams
  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.css
extra_javascript:
  # Config for diagrams
  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.min.js
