[package]
name = "relay-profiling"
authors = ["Sentry <oss@sentry.io>"]
description = "Profiling processing for Relay"
homepage = "https://getsentry.github.io/relay/"
repository = "https://github.com/getsentry/relay"
version = "24.2.0"
edition = "2021"
license-file = "../LICENSE.md"
publish = false

[dependencies]
android_trace_log = { version = "0.3.0", features = ["serde"] }
chrono = { workspace = true }
data-encoding = "2.3.3"
itertools = { workspace = true }
relay-base-schema = { path = "../relay-base-schema" }
relay-event-schema = { path = "../relay-event-schema" }
relay-log = { path = "../relay-log" }
relay-protocol = { path = "../relay-protocol" }
serde = { workspace = true }
serde_json = { workspace = true }
serde_path_to_error = "0.1.14"
thiserror = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
serde_test = "1.0.125"
