[package]
name = "relay-profiling"
authors = ["Sentry <oss@sentry.io>"]
description = "Profiling processing for Relay"
homepage = "https://getsentry.github.io/relay/"
repository = "https://github.com/getsentry/relay"
version = "24.5.1"
edition = "2021"
license-file = "../LICENSE.md"
publish = false

[lints]
workspace = true

[dependencies]
android_trace_log = { workspace = true, features = ["serde"] }
chrono = { workspace = true }
data-encoding = { workspace = true }
itertools = { workspace = true }
relay-base-schema = { workspace = true }
relay-event-schema = { workspace = true }
relay-log = { workspace = true }
relay-metrics = { workspace = true }
relay-protocol = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_path_to_error = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
