[package]
name = "relay-otel"
authors = ["Sentry <oss@sentry.io>"]
description = "OpenTelemetry to Sentry transformation utilities"
homepage = "https://getsentry.github.io/relay/"
repository = "https://github.com/getsentry/relay"
version = "25.11.0"
edition = "2024"
license-file = "../LICENSE"
publish = false

[lints]
workspace = true

[dependencies]
opentelemetry-proto = { workspace = true, features = [
    "gen-tonic",
    "with-serde",
    "trace",
    "logs",
] }
relay-event-schema = { workspace = true }
relay-protocol = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
