[package]
name = "relay-aws-extension"
authors = ["Sentry <oss@sentry.io>"]
description = "AWS extension implementation for Sentry's AWS Lambda layer"
homepage = "https://getsentry.github.io/relay/"
repository = "https://github.com/getsentry/relay"
version = "22.8.0"
edition = "2018"
license-file = "../LICENSE"
publish = false

[dependencies]
actix = "0.7.9"
failure = "0.1.8"
futures01 = { version = "0.1.28", package = "futures" }
relay-log = { path = "../relay-log" }
relay-system = { path = "../relay-system" }
reqwest = { version = "0.11.1", features = ["json", "blocking"] }
serde = { version = "1.0.114", features = ["derive"] }
serde_json = "1.0.55"
tokio = { version = "1.0", features = ["rt-multi-thread"] } # in sync with reqwest
