[package]
name = "bench-buffer"
version = "0.1.0"
authors = ["Sentry <oss@sentry.io>"]
description = "Generates documentation for metrics"
homepage = "https://getsentry.github.io/relay/"
repository = "https://github.com/getsentry/relay"
edition = "2024"
publish = false

[dependencies]
bytes = { workspace = true }
clap = { workspace = true, features = ["derive"] }
rand = { workspace = true }
relay-config = { path = "../../relay-config" }
relay-log = { path = "../../relay-log" }
relay-server = { path = "../../relay-server" }
serde_json = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true }
chrono = { workspace = true }
