[package]
authors = ["Sentry <hello@sentry.io>"]
description = "A helper library for managing different aortas"
documentation = "https://docs.rs/smith-trove"
homepage = "https://github.com/getsentry/sentry-relay"
license = "MIT"
name = "smith-trove"
repository = "https://github.com/getsentry/sentry-relay"
version = "0.1.0"

[dependencies]
failure = "0.1.1"
failure_derive = "0.1.1"
futures = "0.1.21"
log = "0.4.1"
parking_lot = "0.5.5"
tokio-core = "0.1.17"
hyper = "0.11.25"
hyper-tls = "0.1.3"
native-tls = "0.1.5"
serde_json = "1.0.17"
serde = "1.0.45"
serde_derive = "1.0.45"

[dependencies.smith-aorta]
path = "../aorta"
version = "0.1.0"

[dependencies.smith-common]
path = "../common"
version = "0.1.0"
