[package]
name = "semaphore-general-derive"
version = "0.4.16"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]
edition = "2018"

[dependencies]
quote = "0.6.10"
syn = "0.15.24"
synstructure = "0.10.1"
proc-macro2 = "0.4.24"

[lib]
proc-macro = true
