[package]
name = "semaphore-general-derive"
version = "0.4.50"
authors = ["Armin Ronacher <armin.ronacher@active-4.com>"]
edition = "2018"

[dependencies]
quote = "0.6.13"
syn = "0.15.42"
synstructure = "0.11.0"
proc-macro2 = "0.4.30"

[lib]
proc-macro = true
