[package]
authors = ["Sentry <hello@sentry.io>"]
description = "The relay <-> backend communcation and authentication protocol"
documentation = "https://docs.rs/smith-common"
homepage = "https://github.com/getsentry/sentry-relay"
license = "MIT"
name = "smith-aorta"
repository = "https://github.com/getsentry/sentry-relay"
version = "0.1.0"

[dependencies]
base64 = "0.9.1"
failure = "0.1.1"
failure_derive = "0.1.1"
futures = "0.1.18"
hyper = "0.11.25"
hyper-tls = "0.1.3"
parking_lot = "0.5.4"
rand = "0.4.2"
serde = "1.0.43"
serde_derive = "1.0.43"
serde_json = "1.0.16"
sodiumoxide = "0.0.16"
tokio-core = "0.1.17"
url = "1.7.0"

[dependencies.chrono]
features = ["serde"]
version = "0.4.2"

[dependencies.smith-common]
path = "../common"
version = "0.1.0"

[dependencies.uuid]
features = ["v4", "serde"]
version = "0.6.3"
