[package]
authors = ["Sentry <hello@sentry.io>"]
description = "The agent <-> backend communcation and authentication protocol"
documentation = "https://docs.rs/smith-common"
homepage = "https://github.com/getsentry/sentry-relay"
license = "MIT"
name = "smith-aorta"
repository = "https://github.com/getsentry/sentry-relay"
version = "0.1.0"

[dependencies]
base64 = "0.9.0"
failure = "0.1.1"
failure_derive = "0.1.1"
futures = "0.1.17"
hyper = "0.11.18"
hyper-tls = "0.1.2"
parking_lot = "0.5.3"
rand = "0.4.2"
serde = "1.0.27"
serde_derive = "1.0.27"
serde_json = "1.0.9"
sodiumoxide = "0.0.16"
tokio-core = "0.1.12"
url = "1.6.0"

[dependencies.chrono]
features = ["serde"]
version = "0.4.0"

[dependencies.smith-common]
path = "../common"
version = "0.1.0"

[dependencies.uuid]
features = ["v4", "serde"]
version = "0.6.0"
