[package]
name = "semaphore-cabi"
version = "0.4.7"
license = "MIT"
authors = ["Sentry <hello@sentry.io>"]
homepage = "https://github.com/getsentry/semaphore"
repository = "https://github.com/getsentry/semaphore"
description = "Exposes some internals of the relay to C."
edition = "2018"

[lib]
name = "semaphore"
crate-type = ["cdylib"]

[workspace]

[profile.release]
debug = true
lto = true

[dependencies]
chrono = "0.4.6"
failure = "0.1.5"
serde = {version = "1.0.85", features = ["derive"]}
serde_json = "1.0.36"
uuid = "0.7.1"
python-json-read-adapter = { version = "*", git = "https://github.com/untitaker/python-json-read-adapter", branch = "fix/backtrack" }

[dependencies.semaphore-common]
path = "../common"

[dependencies.semaphore-general]
path = "../general"
