[package]
name = "semaphore-cabi"
version = "0.1.0"
license = "MIT"
authors = ["Sentry <hello@sentry.io>"]
homepage = "https://github.com/getsentry/semaphore"
repository = "https://github.com/getsentry/semaphore"
description = "Exposes some internals of the relay to C."

[lib]
name = "semaphore"
crate-type = ["cdylib"]

[workspace]

[profile.release]
debug = true
lto = true

[dependencies]
semaphore-aorta = { version = "0.1.0", path = "../aorta" }
failure = "0.1.1"
uuid = "0.6.3"
serde_json = "1.0.17"
chrono = "0.4.2"
serde_derive = "1.0.45"
serde = "1.0.45"
