[package]
name = "relay-test"
authors = ["Sentry <oss@sentry.io>"]
description = "Test utilities for Relay"
homepage = "https://getsentry.github.io/relay/"
repository = "https://github.com/getsentry/relay"
version = "23.9.1"
edition = "2021"
license-file = "../LICENSE"
publish = false

[dependencies]
relay-log = { path = "../relay-log", features = ["test"] }
relay-system = { path = "../relay-system" }
tokio = { workspace = true }
