[package]
name = "relay-test"
authors = ["Sentry <oss@sentry.io>"]
description = "Test utilities for Relay"
homepage = "https://getsentry.github.io/relay/"
repository = "https://github.com/getsentry/relay"
version = "22.7.0"
edition = "2018"
license-file = "../LICENSE"
publish = false

[dependencies]
actix = "0.7.9"
actix-web = { version = "0.7.19", default-features = false}
futures01 = { version = "0.1.28", package = "futures" }
relay-log = { path = "../relay-log", features = ["test"] }
tokio-timer = "0.2.13"
