[package]
name = "relay-monitors"
authors = ["Sentry <oss@sentry.io>"]
description = "Monitors processing for Relay"
homepage = "https://getsentry.github.io/relay/"
repository = "https://github.com/getsentry/relay"
version = "23.9.0"
edition = "2021"
license-file = "../LICENSE"
publish = false

[dependencies]
once_cell = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
similar-asserts = { workspace = true }
