[package]
name = "relay-monitors"
authors = ["Sentry <oss@sentry.io>"]
description = "Monitors processing for Relay"
homepage = "https://getsentry.github.io/relay/"
repository = "https://github.com/getsentry/relay"
version = "23.8.0"
edition = "2021"
license-file = "../LICENSE"
publish = false

[dependencies]
relay-common = { path = "../relay-common" }
serde = { version = "1.0.114", features = ["derive"] }
serde_json = "1.0.55"
regex = "1.9.1"
once_cell = "1.13.1"
thiserror = { workspace = true }

[dev-dependencies]
similar-asserts = "1.4.2"
