[package]
name = "relay-dynamic-config"
authors = ["Sentry <oss@sentry.io>"]
description = "Dynamic configuration passed down from sentry"
homepage = "https://getsentry.github.io/relay/"
repository = "https://github.com/getsentry/relay"
version = "23.8.0"
edition = "2021"
license-file = "../LICENSE"
publish = false

[features]
default = []

[dependencies]
anyhow = "1.0.66"
assert-json-diff = "2.0.2"
relay-auth = { path = "../relay-auth" }
relay-base-schema = { path = "../relay-base-schema" }
relay-common = { path = "../relay-common" }
relay-filter = { path = "../relay-filter" }
relay-event-normalization = { path = "../relay-event-normalization" }
relay-pii = { path = "../relay-pii" }
relay-quotas = { path = "../relay-quotas" }
relay-sampling = { path = "../relay-sampling" }
serde = { version = "1.0.114", features = ["derive"] }
serde_json = "1.0.55"
smallvec = "1.10.0"

[dev-dependencies]
insta = "1.26.0"
similar-asserts = "1.4.2"
